### ISSUE TITLE
twilio-flex.min.js:142 Error: only absolute urls are supported

### ISSUE THREAD

**Issue by arielsand** [twilio-professional-services/plugin-chat-sms-transfer#15]
Hi I'm getting this error and don know were to look to solve it
Error: only absolute urls are supported
    at plugin-chat-sms-transfer.js:11501
    at new Promise (<anonymous>)
    at new Fetch (plugin-chat-sms-transfer.js:11496)
    at Fetch (plugin-chat-sms-transfer.js:11487)
    at transferOverride (plugin-chat-sms-transfer.js:30222)
    at plugin-chat-sms-transfer.js:30206
    at e.<anonymous> (twilio-flex.min.js:142)
    at twilio-flex.min.js:142
    at Object.next (twilio-flex.min.js:142)
    at twilio-flex.min.js:142
    at new Promise (<anonymous>)
    at r (twilio-flex.min.js:142)
    at e.invokeAction (twilio-flex.min.js:142)
    at Object.<anonymous> (twilio-flex.min.js:142)
    at twilio-flex.min.js:142
    at Object.next (twilio-flex.min.js:142)
    at twilio-flex.min.js:142
    at new Promise (<anonymous>)

**Comment by johnfischelli** [comment]
Hey @arielsand - sorry - still working on making sure the documentation and setup is clear and may be failing a bit. After deploying the Twilio functions, have you defined the `FUNCTION_DOMAIN` constant in your version of the plugin?

https://github.com/twilio-professional-services/plugin-chat-sms-transfer/blob/master/src/ChatTransferPlugin.js#L9

**Comment by arielsand** [comment]
Thanks for your replay, I got to that point but did'n know were to look for that value. 
Sorry I'm new on this field.

**Comment by johnfischelli** [comment]
No problem, I understand.

The basic idea here is that we need to host some server side code that will take the request from the Flex UI and make changes to TaskRouter through the Twilio REST API. We provide the code for this, and it is ready to go and be deployed to a Twilio Serverless function, and it is [contained in the functions directory of this repo](https://github.com/twilio-professional-services/plugin-chat-sms-transfer/tree/master/functions).

You'll need to make sure you've installed the [Twilio-Cli](https://www.twilio.com/docs/twilio-cli/quickstart) and then install the [serverless toolkit](https://www.twilio.com/docs/labs/serverless-toolkit/getting-started#install-the-twilio-serverless-toolkit) as a plugin to the Twilio-Cli.

Once you've installed both, navigate into the functions directory of this repo and `npm install`.

Once that completes, you should be able to run `twilio serverless:deploy` which will connect to your twilio account (you set it up when installing the Twilio-Cli) and deploy the necessary function for you to transfer chats. The output from the `twilio serverless:deploy` function will look like this:

```
...
Deployment Details
Domain: plugin-chat-sms-transfer-functions-8308-dev.twil.io
...
```
This domain value is what you should set into the `SEVERLESS_FUNCTION_DOMAIN` value in the plugin!

---

Alternatively, if you don't want to use a Twilio serverless function to host the necessary code - you can review the actions being taken in the [function itself](https://github.com/twilio-professional-services/plugin-chat-sms-transfer/blob/master/functions/functions/transfer-chat.js) and re-write them and host them in your own application using whatever backend language you want. But we provide the serverless function to get you up and running quicker.

**Comment by johnfischelli** [comment]
I forgot to mention that before deploying the function there are some `.env` [variables you should set](https://github.com/twilio-professional-services/plugin-chat-sms-transfer#required-env-variables-in-your-function).

**Comment by somentelucas** [comment]
I'm still getting this error:

<img width="308" alt="Captura de Tela 2021-01-22 às 14 42 38" src="https://user-images.githubusercontent.com/4432322/105526627-6c477d00-5cc1-11eb-94b4-f81cf5d0aa11.png">

I have configured the domain in the `SERVERLESS_FUNCTION_DOMAIN` variable in `/src/helpers/actions.js` as specified in the documentation:

![Captura de Tela 2021-01-22 às 14 49 32](https://user-images.githubusercontent.com/4432322/105526385-1b378900-5cc1-11eb-9d1c-8d139cf00c61.png)

And also configured the `/functions/.env` file:

![Captura de Tela 2021-01-22 às 14 50 44](https://user-images.githubusercontent.com/4432322/105526510-4b7f2780-5cc1-11eb-89c9-601734a05e44.png)

Is there anything else I'm missing?

**Comment by johnfischelli** [comment]
@somentelucas it looks like you're missing the protocol in the `SERVERLESS_FUNCTION_DOMAIN` so adding `https://` should suffice! Sorry we may need to clean up the docs, its gone through several iterations and its possible we missed something!
