### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by jonhooton** [twilio-professional-services/plugin-chat-sms-transfer#18]
Hi there,

I am receiving the below CORS rejection when attempting to transfer. I'm sure I am missing something, but not sure where to look. Can anyone point me in the right direction? Thanks!

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at [my-twiloi-url]. (Reason: header ‘user-agent’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).`

**Comment by johnfischelli** [comment]
Hey @jonhooton, might need a little more detail from you, but it looks like there may be a typo in your code based on the error. The error states `my-twiloi-url` and I imagine you may have meant `my-twilio-url`. I assume this is some variable or such that you have defined yourself!

Let me know if that is the issue!

**Comment by jonhooton** [comment]
Hi @johnfischelli  - Thanks for the quick reply. That was an intentional removal, the actual URL points to my twilio transfer-chat function. I can provide my URL if helpful.

**Comment by johnfischelli** [comment]
No problem, there was a recent PR #11 that introduced new CORS headers. Its possible we may have broken the issue there. I will do some more testing. For the moment you can replace the headers in your `transfer-chat` function back to the previous versions.

```// setup a response object
	const response = new Twilio.Response();
	response.appendHeader('Access-Control-Allow-Origin', '*');
	response.appendHeader('Access-Control-Allow-Methods', 'OPTIONS POST');
	response.appendHeader('Content-Type', 'application/json');
	response.appendHeader('Access-Control-Allow-Headers', 'Content-Type');```

And see if you have more luck.

**Comment by johnfischelli** [comment]
Also for later testing it might be helpful to know what browser/version you're testing with.

**Comment by jonhooton** [comment]
@johnfischelli I am still getting the same error while using Firefox 77.0.1. When I test in Chrome 84.0.4147.89 I get an error, but slightly different content (screenshot below).
![Screen Shot 2020-07-28 at 11 17 10 AM](https://user-images.githubusercontent.com/33834719/88692853-29b33800-d0c4-11ea-8ed5-36ed5c90c49e.png)

**Comment by johnfischelli** [comment]
Can you use the browser console to identify the pre-flight request, right click it, copy it as curl and paste it here. Feel free to redact your URL if necessary.

```
curl 'https://MY-TWILIO-URL-dev.twil.io/transfer-chat' \
  -X 'OPTIONS' \
  -H 'authority: MY-TWILIO-URL-dev.twil.io' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'accept: */*' \
  -H 'access-control-request-method: POST' \
  -H 'access-control-request-headers: content-type' \
  -H 'origin: http://localhost:3000' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-dest: empty' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36' \
  -H 'accept-language: en-US,en;q=0.9' \
  --compressed
```

I'm particularly interested in `  -H 'access-control-request-headers: content-type' \` what access-control-request-headers you're pre flight is sending.

**Comment by johnfischelli** [comment]
Nevermind, I just re-read your initial error and its clearly the user-agent! I'll link you to the PR that should fix it!

**Comment by jonhooton** [comment]
@johnfischelli Great! Thanks!

**Comment by johnfischelli** [comment]
@jonhooton - Wow, this is super crazy. I'm still researching and checking with other engineers here at Twilio but I don't think the function we deploy handles the preflight request, but rather the Twilio serverless platform appears to handle it. The Twilio serverless platform sets CORS headers and doesn't contain `user-agent` which Firefox sends in its preflight.

Strangely enough the Chrome preflight is working just fine for me, so harder to speak to the error you saw in Chrome. I'll see if we can add the required header to make Firefox work, but its going to take longer.

**Comment by johnfischelli** [comment]
Confirmed the issue is with the Twilio platform not this individual transfer function. We have a fix merged and expect it to rollout on the platform either later today or maybe tomorrow, will update this issue when its resolved.

**Comment by johnfischelli** [comment]
Hey @jonhooton we rolled out a fix for handling preflight requests on Firefox. They are now working for me.

**Comment by jonhooton** [comment]
@johnfischelli Thank you for your help on this! We are operational now!

**Comment by jonathan-vouch** [comment]
@johnfischelli I have been speaking to Rex Beatie at Twilio Support for this for a while now.  Ticket # 4426657 if you want to take a look :)

**Comment by johnfischelli** [comment]
@jonathan-vouch Sure, I'll take a look. I had to request access so it may be a day or two before I get a chance.

**Comment by somentelucas** [comment]
Hi @johnfischelli , I'm facing the same issue. Do you think this might still be happening for some cases? I've copied the request the browser has done as a CURL  and this is what I've got:

```
curl 'https://plugin-chat-sms-transfer-functions-9286-dev.twil.io/transfer-chat' \
  -H 'authority: plugin-chat-sms-transfer-functions-9286-dev.twil.io' \
  -H 'accept: */*' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'origin: https://flex.twilio.com' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'accept-language: pt,en;q=0.9,en-US;q=0.8,fr;q=0.7,gl;q=0.6' \
  --data-raw '{"Token":"..."}' \
  --compressed
```

Still not sure it's something I'm doing wrong or an issue with the platform :/

**Comment by johnfischelli** [comment]
Hey @somentelucas! Thanks for bringing this up. Its possible there is an issue with the Twilio runtime platform - as was previously the case with this issue. Let me perform some tests and ask around at Twilio internally and see what comes up. The last time I touched this plugin it was all working, but software always changes and its possible it needs another adjustment!

**Comment by somentelucas** [comment]
Ok, many thanks @johnfischelli! I'll wait for your reply then 😄

**Comment by timeprodutos** [comment]
Hi @johnfischelli were you able to find something about it?

**Comment by somentelucas** [comment]
Hi @johnfischelli, were you able to find out about it?

**Comment by johnfischelli** [comment]
Hey @somentelucas, not yet. Planning to take a look over the weekend and will report back.
