### ISSUE TITLE
Can't transfer webchat

### ISSUE THREAD

**Issue by cspangge** [twilio-professional-services/plugin-chat-sms-transfer#33]
Hi, I follow the instruction to implement transfer webchat feature. But I got error message when I click transfer to other agent.

![image](https://user-images.githubusercontent.com/54304611/98285755-213d9800-1ff7-11eb-9015-24e18a5910c2.png)

**Comment by johnfischelli** [comment]
Hey @cspangge,

I need to adjust the plugin a bit, but what I think is happening here is that the Twilio function is either not being called or has failed to perform the transfer. In the event that an error is encountered during the transfer, we try to rejoin you to the chat channel, but if you never left it in the first place you'll see this error.

The first and most common thing to check is when you deployed the function and it was assigned a URL, make sure you add the protocol when you update the plugin with your function URL ... `https://....`. Our docs don't mention that but it is important!

**Comment by cspangge** [comment]
@johnfischelli Hi, John. Thanks for your reply. Lets me try to update function URL and see if issue can be fixed.

**Comment by cspangge** [comment]
@johnfischelli  Since change function URL, it shows CORS error message. 

Access to fetch at 'https://plugin-chat-sms-transfer-functions-4695-dev.twil.io/transfer-chat' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by cspangge** [comment]
@johnfischelli  Access to fetch at 'https://plugin-chat-sms-transfer-functions-4695-dev.twil.io/transfer-chat' from origin 'https://flex.twilio.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by cspangge** [comment]
@johnfischelli Hi, John. I will mark this issue has been resolved by updating function URL. Thank you for your support.
