### ISSUE TITLE
Task not assigned to a particular queue

### ISSUE THREAD

**Issue by SandeepReddyPinniti** [twilio-professional-services/plugin-chat-sms-transfer#37]
Hi,

We are assigning the task to a queue instead of an agent, the task won't get assigned to an agent in the queue instead the task is assigned back to someone else in the old queue.

Thanks...

**Comment by johnfischelli** [comment]
Hi @SandeepReddyPinniti - unfortunately the plugin can't configure your workflow for you and what you're describing sounds like the workflow is misconfigured. If you'd like to paste relevant workflow rules here, I can possibly help.

If you haven't already seen this - we provide a sample workflow to show you how it might work here: [](https://www.twilio.com/docs/flex/solutions-library/chat-and-sms-transfers-flex#create-a-new-taskrouter-workflow)

**Comment by SandeepReddyPinniti** [comment]
Hi John,

Firstly I thought based on the Queue Name and Worker Name the chat transfer takes care of assigning to the right person or queue by itself. Based on my initial assumption I opened this ticket. I have implemented additional logic on our system to handle chat transfer. Sorry for the trouble.

Close the ticket. Thanks for your plugin, it helps a lot.
