### ISSUE TITLE
Spinning wheel after transfer

### ISSUE THREAD

**Issue by maxmito** [twilio-professional-services/plugin-chat-sms-transfer#44]
Hello,
when trying to transfer a chat to agent or queue I get spinning wheel and nothing happens, no error in Debugger, no error in Web Browser Console (see image below).
The only action I can do is to end the chat , if I try to transfer it again to queue or agent, still spinning wheel.
Any idea what could be the issue?

Max

![spinning](https://user-images.githubusercontent.com/4243047/117359785-3026d980-aeb8-11eb-94ce-e3d661413363.png)

**Comment by maxmito** [comment]
Not sure if relevant, but the only error I can see is about Source Map (but I can disable it)

Source map error: Error: request failed with status 403
Resource URL: https://assets.flex.twilio.com/releases/flex-ui/1.25.4/twilio-flex.min.js
Source Map URL: twilio-flex.prod.browser.js.map

in the browser console I see the XHR request to transfer-chat Function is successful (200)

**Comment by bermudezmt** [comment]
Hey @maxmito , what version of the Flex UI are you running and on what OS? If you followed the guide at https://www.twilio.com/docs/flex/solutions-library/chat-and-sms-transfers, you should see a list of tested versions. I'm afraid we've last tested this on 1.23.1

**Comment by maxmito** [comment]
At the end for me it worked creating new Task Workflow and filter as per  [https://www.twilio.com/docs/flex/solutions-library/chat-and-sms-transfers](https://www.twilio.com/docs/flex/solutions-library/chat-and-sms-transfers), without that I had issues.
Thanks!
